services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: axumlive_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
